name: Build Windows .exe

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - uses: actions/setup-haskell@v1.1
      with:
        enable-stack: true
        stack-version: 'latest'

    - name: Install Dependencies
      run: stack install

    - name: Build
      run: stack build
