name: Build Windows .exe

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install QT
      run: |
        curl -L https://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe > qt-unified-windows-x86-online.exe
        ls
        D:\a\r34-downloader\r34-downloader\qt-unified-windows-x86-online install --root C:\QT\MyQt --accept-licenses --accept-obligations --default-answer --confirm-command

    - uses: actions/setup-haskell@v1.1
      with:
        enable-stack: true
        stack-version: 'latest'

    - name: Install Dependencies
      run: stack install

    - name: Build
      run: stack build
